
vscode:
  extensions:
    - 42Crunch.vscode-openapi

tasks:
  - name: aws-cli 
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      sudo apt-get update
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      echo 'AWS CLI v2 installed successfully'
      cd $THEIA_WORKSPCE_ROOT
    command: We're ready to go!'